name: Lint

on:
  pull_request:
    branches: master

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-deploy-${{hashFiles('**/package-lock.json')}}
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm ci
      - run: npx tsc --noEmit
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master
      - run: npx eslint $(git diff-index --name-only --diff-filter=AM origin/master -- "*.js" "*.jsx" "*.ts" "*.tsx")
